<?php
$z[0]=Array("field","",346,365);
$z[0][4]['name']="title";
$z[1]=Array("global","",366,392);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",433,455);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",495,546);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1046,1081);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1701,1759);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n          <li><a  href=\"[field:typeurl/]\"><font>></font>[field:typename/]</a></li>\r\n          ",1814,2065);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='cur_left'><font>></font>~typename~</a></li>";
$z[7]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\"  title=\"[field:title/]\"><img src=\"[field:picname/]\" /><span>[field:title/]</span></a></li>\r\n              ",2279,2490);
$z[7][4]['row']="12";
$z[7][4]['titlelen']="32";
$z[7][4]['typeid']="6";
$z[8]=Array("field","",2630,2659);
$z[8][4]['name']="position";
$z[9]=Array("field","",2674,2703);
$z[9][4]['name']="typename";
$z[10]=Array("field","",2759,2778);
$z[10][4]['name']="title";
$z[11]=Array("field","",2797,2823);
$z[11][4]['name']="image";
$z[12]=Array("field","",2963,2981);
$z[12][4]['name']="body";
$z[13]=Array("arclist","\r\n            <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" /><span>[field:title/]</span></a></li>\r\n            ",3115,3310);
$z[13][4]['row']="4";
$z[13][4]['typeid']="26";
$z[14]=Array("include","",3385,3422);
$z[14][4]['filename']="footer.htm";

?>