<?php
$z[0]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n<li>|</li>\r\n",122,340);
$z[0][4]['type']="top";
$z[0][4]['row']="6";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("type","\r\n<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n",342,439);
$z[1][4]['typeid']="32";
$z[2]=Array("global","",451,472);
$z[2][4]['name']="cfg_lx";
$z[3]=Array("global","",474,500);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",542,566);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("flink","\r\n<li> [field:link /] </li>\r\n<li>|</li>\r\n",753,854);
$z[5][4]['titlelen']="20";
$z[5][4]['row']="20";
$z[5][4]['type']="text";
$z[6]=Array("global","",1046,1068);
$z[6][4]['name']="cfg_qqa";
$z[7]=Array("global","",1233,1255);
$z[7][4]['name']="cfg_qqb";
$z[8]=Array("global","",1420,1442);
$z[8][4]['name']="cfg_qqc";
$z[9]=Array("global","",2301,2323);
$z[9][4]['name']="cfg_qqa";
$z[10]=Array("global","",2427,2449);
$z[10][4]['name']="cfg_qqb";
$z[11]=Array("global","",2553,2575);
$z[11][4]['name']="cfg_qqc";

?>