<?php
$z[0]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",70,164);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",168,262);
$z[1][4]['typeid']="6";
$z[2]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",266,361);
$z[2][4]['typeid']="21";
$z[3]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",365,460);
$z[3][4]['typeid']="25";
$z[4]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",464,559);
$z[4][4]['typeid']="27";
$z[5]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",563,658);
$z[5][4]['typeid']="29";
$z[6]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",662,757);
$z[6][4]['typeid']="31";
$z[7]=Array("global","",802,828);
$z[7][4]['name']="cfg_address";
$z[8]=Array("global","",852,878);
$z[8][4]['name']="cfg_dianhua";
$z[9]=Array("global","",899,921);
$z[9][4]['name']="cfg_qqa";

?>