<?php
$z[0]=Array("flink","\r\n      <li> [field:link /] </li>\r\n      <li>|</li>\r\n      ",109,228);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        <li>|</li>\r\n        ",496,754);
$z[1][4]['type']="top";
$z[1][4]['row']="6";
$z[1][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[2]=Array("type","\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",764,877);
$z[2][4]['typeid']="32";
$z[3]=Array("global","",901,922);
$z[3][4]['name']="cfg_lx";
$z[4]=Array("global","",932,958);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1000,1024);
$z[5][4]['name']="cfg_beian";

?>