<?php
$z[0]=Array("global","",322,349);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",501,527);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" class=\"\">[field:typename/]</a></li>\r\n      ",802,1048);
$z[2][4]['type']="top";
$z[2][4]['row']="7";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' class='abcd'><span>~typename~</span></a></li>";

?>