<?php
$z[0]=Array("global","",130,156);
$z[0][4]['name']="cfg_dianhua";
$z[1]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",250,344);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",355,449);
$z[2][4]['typeid']="6";
$z[3]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",460,555);
$z[3][4]['typeid']="21";
$z[4]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",566,661);
$z[4][4]['typeid']="25";
$z[5]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",672,767);
$z[5][4]['typeid']="27";
$z[6]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",778,873);
$z[6][4]['typeid']="29";
$z[7]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",884,979);
$z[7][4]['typeid']="31";

?>