<?php
$z[0]=Array("global","",178,204);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",245,274);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",314,372);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("php","\r\npasterTempletDiy(\"wap/head.htm\");\r\n",832,890);
$z[4]=Array("field","",952,974);
$z[4][4]['name']="position";
$z[5]=Array("channel","\r\n<li><a href='/waplist.php?tid=[field:id/]'>[field:typename/]</a></li>\r\n",1006,1201);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a class='a1' href='/waplist.php?tid=~id~'>~typename~</a></li>";
$z[6]=Array("php","\r\npasterTempletDiy(\"wap/footer.htm\");\r\n",4211,4271);

?>