<?php
$z[0]=Array("field","",346,365);
$z[0][4]['name']="title";
$z[1]=Array("global","",366,392);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",433,462);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",502,560);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1057,1092);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1854,1912);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n          <li><a  href=\"[field:typeurl/]\"><font>></font>[field:typename/]</a></li>\r\n          ",1964,2215);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='cur_left'><font>></font>~typename~</a></li>";
$z[7]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\"  title=\"[field:title/]\"><img src=\"[field:picname/]\" /><span>[field:title/]</span></a></li>\r\n              ",2430,2641);
$z[7][4]['row']="12";
$z[7][4]['titlelen']="32";
$z[7][4]['typeid']="6";
$z[8]=Array("field","",2781,2810);
$z[8][4]['name']="position";
$z[9]=Array("field","",2825,2854);
$z[9][4]['name']="typename";
$z[10]=Array("list","\r\n          <li><a href='[field:picname/]' class='fresco' data-fresco-group='example' data-fresco-caption=\"[field:title/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\"/><span>[field:title/]</span></a></li>\r\n          ",2922,3181);
$z[10][4]['pagesize']="9";
$z[11]=Array("pagelist","",3257,3310);
$z[11][4]['listitem']="index,end,pre,next,pageno";
$z[12]=Array("include","",3356,3393);
$z[12][4]['filename']="footer.htm";

?>