<?php
$z[0]=Array("global","",356,382);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",423,452);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",492,550);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1047,1082);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n          <li><a  href=\"[field:typeurl/]\"><font>></font>[field:typename/]</a></li>\r\n          ",1771,2033);
$z[4][4]['type']="son";
$z[4][4]['typeid']="6";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='cur_left'><font>></font>~typename~</a></li>";
$z[5]=Array("arclist","\r\n            <li><a href=\"[field:arcurl/]\"  title=\"[field:title/]\"><img src=\"[field:picname/]\" /><span>[field:title/]</span></a></li>\r\n            ",2207,2414);
$z[5][4]['row']="12";
$z[5][4]['titlelen']="32";
$z[5][4]['typeid']="6";
$z[6]=Array("global","",2603,2658);
$z[6][4]['name']="keyword";
$z[6][4]['function']="RemoveXSS(@me)";
$z[7]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\"/><span>[field:title/]</span></a></li>\r\n          ",2738,2916);
$z[7][4]['perpage']="20";
$z[8]=Array("pagelist","",2992,3045);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",3091,3128);
$z[9][4]['filename']="footer.htm";

?>